<?php

namespace AppBundle\Repository;

/**
 * IPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IPRepository extends \Doctrine\ORM\EntityRepository
{
}
