ip.search:
    path: /
    controller: 'AppBundle\Controller\DefaultController::indexAction'

ip.save:
    path: /save
    methods: [POST, PUT]
    controller: 'AppBundle\Controller\DefaultController::saveAction'